'use client';
import {useState} from 'react';
import {ComposedChart,Line,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,BarChart,Bar} from 'recharts';
import {Layers,LayoutDashboard,Pill,Stethoscope,Building2,Users,Calculator,Sun,Moon,ArrowUpRight,ChevronDown,ShieldCheck,Activity,CalendarDays} from 'lucide-react';
const fmt=(v:number)=>v.toLocaleString('ru-RU');
const weeks=['08 июл','15 июл','22 июл','29 июл','05 авг','12 авг','19 авг','26 авг','02 сен','09 сен','16 сен','23 сен','30 сен'];
const source=weeks.map((name,i)=>({name,lp:[185,210,198,265,241,298,285,320,310,355,342,390,372][i],mi:[92,105,88,115,132,120,145,138,165,152,178,165,182][i]}));
const orgs=[['Городская клиническая больница № 52',438],['Городская клиническая больница № 67',376],['НИИ скорой помощи им. Н. В. Склифосовского',324],['Морозовская детская городская больница',281],['Городская клиническая больница № 1',246]] as const;
const colors=['#8583ff','#e665e8'];
export default function Dashboard(){
 const [period,setPeriod]=useState('3');const [service,setService]=useState('all');const [light,setLight]=useState(false);const [group,setGroup]=useState('week');
 const rows=source.slice(period==='1'?-4:period==='6'?0:-13).map(d=>({...d,lp:service==='mi'?0:d.lp,mi:service==='lp'?0:d.mi}));
 const chartRows=group==='week'?rows:rows.reduce((a:any[],r,i)=>{const j=Math.floor(i/4);if(!a[j])a[j]={name:['Июль','Август','Сентябрь','Октябрь'][j],lp:0,mi:0};a[j].lp+=r.lp;a[j].mi+=r.mi;return a},[]);
 const lp=rows.reduce((s,r)=>s+r.lp,0),mi=rows.reduce((s,r)=>s+r.mi,0),total=lp+mi;const active=Math.round(total/45);const max=rows.reduce((a,b)=>a.lp+a.mi>b.lp+b.mi?a:b);
 const tooltip={background:'var(--panel)',border:'1px solid var(--border)',borderRadius:12,color:'var(--text)'};
 return <div className={light?'app light':'app'}><aside className="rail"><div className="brand"><Layers size={25}/></div><button className={service==='all'?'active':''} title="Обзор" aria-label="Обзор" onClick={()=>setService('all')}><LayoutDashboard/></button><button className={service==='lp'?'active':''} title="Лекарственные препараты" aria-label="Лекарственные препараты" onClick={()=>setService('lp')}><Pill/></button><button className={service==='mi'?'active':''} title="Медицинские изделия" aria-label="Медицинские изделия" onClick={()=>setService('mi')}><Stethoscope/></button><div className="rail-bottom"><ShieldCheck size={21}/><span>ДЕМО</span></div></aside>
 <main><header><div className="breadcrumb">АНАЛИТИЧЕСКИЙ ЦЕНТР <span>/</span> ОТЧЁТНОСТЬ</div><div className="header-right"><span className="demo">Демонстрационные данные</span><button className="theme" aria-label="Переключить тему" onClick={()=>setLight(!light)}>{light?<Moon size={19}/>:<Sun size={19}/>}</button><div className="avatar">АЦ</div></div></header>
 <div className="heading"><div><div className="eyebrow">ЦИФРОВЫЕ СЕРВИСЫ</div><h1>Экспертиза закупок</h1><p>Использование сервисов расчёта НМЦК</p></div><label className="period"><CalendarDays size={18}/><select aria-label="Период" value={period} onChange={e=>setPeriod(e.target.value)}><option value="1">Последний месяц</option><option value="3">Последние 3 месяца</option></select><ChevronDown size={16}/></label></div>
 <div className="toolbar"><div className="tabs">{[['all','Все сервисы'],['lp','Лекарственные препараты'],['mi','Медицинские изделия']].map(([id,label])=><button key={id} className={service===id?'selected':''} onClick={()=>setService(id)}>{label}</button>)}</div><span className="snapshot">Срез макета · 07 октября 2026</span></div>
 <section className="kpis">{[{title:'Количество заявителей',value:728,note:'Все зарегистрированные в сервисе ЛП',icon:Users,color:'#5789ff',tag:'За всё время'},{title:'Активные организации',value:active,note:'Выполняли расчёты за период',icon:Building2,color:'#35c9a0',tag:'За выбранный период'},{title:'Выполненные расчёты',value:total,note:service==='all'?'Лекарственные препараты и медизделия':service==='lp'?'Лекарственные препараты':'Медицинские изделия',icon:Calculator,color:'#a48aff',tag:'За выбранный период'}].map((k,i)=><article className="kpi" key={k.title} style={{'--accent':k.color} as any}><div className="kpi-top"><div className="icon"><k.icon size={22}/></div><span>{String(i+1).padStart(2,'0')}</span></div><h2>{k.title}</h2><div className="number">{fmt(k.value)}</div><p>{k.note}</p><div className="kpi-foot"><span>{k.tag}</span><Activity size={17}/></div></article>)}<article className="kpi growth"><div className="kpi-top"><div className="icon"><Activity size={22}/></div><span>04</span></div><h2>Динамика расчётов</h2><div className="number">+18,4<span>%</span></div><p>К предыдущему равному периоду</p><div className="kpi-foot"><span><ArrowUpRight size={16}/> Рост активности</span><svg width="95" height="28" viewBox="0 0 95 28"><path d="M0 26 L10 20 L20 22 L30 12 L40 16 L50 7 L60 11 L70 4 L80 6 L95 0" fill="none" stroke="#35c9a0" strokeWidth="2"/></svg></div></article></section>
 <section className="primary"><article className="panel dynamics"><div className="panel-head"><div><h2>Динамика расчётов</h2><p>Количество выполненных расчётов</p></div><div className="segments"><button className={group==='week'?'chosen':''} onClick={()=>setGroup('week')}>Недели</button><button className={group==='month'?'chosen':''} onClick={()=>setGroup('month')}>Месяцы</button></div></div><div className="legend"><span><i style={{background:colors[0]}}/>Лекарственные препараты</span><span><i style={{background:colors[1]}}/>Медицинские изделия</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartRows} margin={{top:20,right:8,left:-23,bottom:0}}><defs><linearGradient id="indigoBars" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#9392ff"/><stop offset="100%" stopColor="#4a3ada"/></linearGradient><linearGradient id="blue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={colors[0]} stopOpacity={.25}/><stop offset="100%" stopColor={colors[0]} stopOpacity={0}/></linearGradient><linearGradient id="purple" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={colors[1]} stopOpacity={.15}/><stop offset="100%" stopColor={colors[1]} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="name" tick={{fill:'var(--muted)',fontSize:13}} axisLine={false} tickLine={false} minTickGap={25}/><YAxis tick={{fill:'var(--muted)',fontSize:13}} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltip} formatter={(v:any,n:any)=>[fmt(v),n==='lp'?'ЛП':'МИ']}/><Bar dataKey="lp" fill="url(#indigoBars)" radius={[5,5,0,0]} maxBarSize={26}/><Line type="monotone" dataKey="mi" stroke={colors[1]} strokeWidth={3} dot={false} activeDot={{r:6,fill:colors[1],stroke:"#fff",strokeWidth:2}}/></ComposedChart></ResponsiveContainer></div><div className="chart-footer"><span>Расчёты за выбранный период</span><strong>{fmt(total)}</strong></div></article>
 <article className="panel share"><div className="panel-head"><div><h2>Использование сервисов</h2><p>Доля в общем числе расчётов</p></div></div><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{name:'ЛП',value:lp},{name:'МИ',value:mi}]} dataKey="value" innerRadius="72%" outerRadius="92%" startAngle={90} endAngle={-270} stroke="none" paddingAngle={3}>{colors.map(c=><Cell key={c} fill={c}/>)}</Pie><Tooltip contentStyle={tooltip}/></PieChart></ResponsiveContainer><div className="donut-label"><strong>{Math.round((service==='mi'?mi:lp)/total*100)}%</strong><span>{service==='mi'?'МИ — 100%':'сервис ЛП'}</span></div></div><div className="service-row"><i style={{background:colors[0]}}/><span>Лекарственные препараты</span><strong>{fmt(lp)}</strong></div><div className="service-row"><i style={{background:colors[1]}}/><span>Медицинские изделия</span><strong>{fmt(mi)}</strong></div></article></section>
 <section className="secondary"><article className="panel organizations"><div className="panel-head"><div><h2>Активность организаций</h2><p>Пять организаций с наибольшим числом расчётов · пример</p></div><Building2 size={20}/></div>{orgs.map(([name,n],i)=>{const v=Math.round(n*(period==='1'?.35:1)*(service==='all'?1:service==='lp'?.67:.33));return <div className="org" key={name}><span className="rank">0{i+1}</span><div className="org-content"><div><span>{name}</span><strong>{fmt(v)}</strong></div><div className="track"><div style={{width:`${n/438*100}%`,opacity:1-i*.13}}/></div></div></div>})}</article><article className="panel weekly"><div className="panel-head"><div><h2>Активность по неделям</h2><p>Общий объём расчётов ЛП и МИ</p></div></div><div className="bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows.map(r=>({...r,total:r.lp+r.mi}))} margin={{left:-25,right:0,top:20}}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 5"/><XAxis dataKey="name" tick={{fill:'var(--muted)',fontSize:13}} axisLine={false} tickLine={false} minTickGap={30}/><YAxis tick={{fill:'var(--muted)',fontSize:13}} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltip} formatter={(v:any)=>[fmt(v),'Расчётов']}/><Bar dataKey="total" fill="#5789ff" radius={[4,4,0,0]} maxBarSize={23}/></BarChart></ResponsiveContainer></div><div className="peak"><Activity size={18}/><span>Пиковая неделя <strong>{max.name}</strong></span><strong>{fmt(max.lp+max.mi)} расчётов</strong></div></article></section>
 <footer><span><ShieldCheck size={15}/> Визуальный прототип · без подключения к рабочей БД</span><span>Цифровая экспертиза / 2026</span></footer></main></div>
}
